#management:
#  context-path: /admin
#  security:
#    enabled: false

#spring:
#  rabbitmq:
#   host: 192.168.0.195
#    port: 5672
#    username: yoara
#    password: yoara

#spring:
#  rabbitmq:
#    host: 10.251.92.64
#    port: 5672
#    username: qfang
#    password: qfang.ciMG2018